baseURL: /
languageCode: en-us
publishDir: public/
canonifyURLs: true
title: guac
theme: hugo-fresh
googleAnalytics: G-C86QDTQNRG
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/guac-logo-squareish.png
    link: /
    text: GUAC
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Know your software supply chain
    # Hero subtitle (optional)
    subtitle: Use GUAC to get organized and actionable insights into your software supply chain security position. 
    # Button text
    button1text: Now in Beta!
    button1link: "https://github.com/guacsec/guac"

    # Hero image (from static/images/___)
    #image: illustrations/worker.svg
    image: logos/guac-logo.png


    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Community
    url: /community
  - title: Blogs
    url: /blogs
  - title: Demos
    url: https://guac.sh/
  - title: Docs
    url: https://guac.sh/
  - title: Github
    url: https://github.com/guacsec/guac
    button: true


  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  #sidebar:
  #  # Logo (from /images/logos/___.svg)
  #  logo: fresh-square
  #  sections:
  #  - title: User
  #    icon: user
  #    links:
  #    - text: Profile
  #      url: /
  #    - text: Account
  #      url: /
  #    - text: Settings
  #      url: /
  #  - title: Messages
  #    icon: envelope
  #    links:
  #    - text: Inbox
  #      url: /
  #    - text: Compose
  #      url: /
  #  - title: Images
  #    icon: image
  #    links:
  #    - text: Library
  #      url: /
  #    - text: Upload
  #      url: /
  #  - title: Settings
  #    icon: cog
  #    links:
  #    - text: User settings
  #      url: /
  #    - text: App settings
  #      url: /
  
    sectionGithub:
    title: The current problem with software supply chain security
    subtitle: Software supply chain attacks are on the rise and unless you have enterprise-scale security and IT funding, it’s hard to know what your software is at risk for and how to protect it. Many tools are available to help you find Software Bills of Materials (SBOMs), signed attestations, and vulnerabilities, but there’s currently no way to combine and synthesize this information into a comprehensive and actionable view.
    
    sectionUniid:
    title: Our vision
    subtitle: GUAC (Graph for Understanding Artifact Composition), aims to bring disparate sources of software metadata (like SBOMs)  together into one tool to make it easier for organizations to understand their software security position and act at every point in the software development life cycle.
  
    sectionGithub:
    title: GUAC Beta is now open!
    subtitle: In Beta, you can run GUAC internally in your organization to take active steps to manage risk. Currently, you can query SLSA provenance, SBOMs, and OpenSSF Scorecards. In the future, GUAC aims to run as a public service where high-fidelity supply chain security metadata can be attained for every software ecosystem.
    button1Text: Try GUAC out!
    button1Link: hhttps://guac.sh/
  
  
  section1:
    title: What does GUAC do?
    tiles:
    - title: Establishes connections between your software catalog
      icon: mouse-globe
    - title: Unveils gaps in the software supply chain data using other data sources
      icon: laptop-cloud
    - title: Identifies threats in your supply chain and provides a path to remediation
      icon: plug-cloud
     
  section2:
    title: How GUAC can help you
    subtitle: These are just a few examples of insights that GUAC can provide.
    features:
    - title: Proactive
      text: Find the most used critical components in a software supplay chaing ecosytem. 
            Find weaknesses in overall security posture.
            Prevent supply chain compromises before they happen.
            Find exposures to risky dependencies.
      icon: laptop-globe
    - title: Operational
      text: Look for evidence that the application you're about to deploy meets your organizations policies.
            Track if all binaries in production trace back to a securely managed repository.
    - title: Reactive
      text: Find which parts of your organization's inventory are affected by a new vulnerability.
            Track a suspivious project lifecycle event back to the risk that was introduced into your organization.
            Learn how an open source project deprecation affects you.
      icon: doc-sync



    sectionGithub:
    title: A collaboration between
    subtitle: Citi, Google,  Kusari, Purdue University 



  sectionGithub:
    title: What's next?
    subtitle: Learn more about GUAC
    button1Text: Github
    button1Link: https://github.com/guacsec/guac
    button2Text: FAQ
    button2Link: /faq

  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
